#! /bin/sh


# Ymparistomuuttuja $DCT_DATA_DIR taytyy olla asetettu!
# Se kertoo, mihin hakemistoon fiilut kaannetaan

clear

DCT_DATA_DIR="D:\tmp\Dct"
HIBI_CVS_TREE=../../../../../../Hibi/Hibi
HIBI_SRC_DIR=$HIBI_CVS_TREE/IP/Interconnections/Hibi/Hibi_v2/Vhdl/Ver_05
DCT_WORK_DIR=..
DCTQIDCT_DIR=../../..

echo 'Creating makefile'

if test ! -d ${DCT_DATA_DIR}
then
  echo 'Tehdaan /tmp:iin projektille hakemistorakenne...'
  echo '($DCT_DATA_DIR =' $DCT_DATA_DIR ')'	
  mkdir $DCT_DATA_DIR
fi

# Poistetaan vanha library ja tehdaan uusi
echo "Remove old vhdl library and create new "
rm -rf $DCT_DATA_DIR\\codelib
rm -rf $DCT_DATA_DIR\\common_da
rm -rf $DCT_DATA_DIR\\dct
rm -rf $DCT_DATA_DIR\\idct
rm -rf $DCT_DATA_DIR\\quantizer
rm -rf $DCT_DATA_DIR\\dctQidct

vlib $DCT_DATA_DIR\\codelib
vlib $DCT_DATA_DIR\\common_da
vlib $DCT_DATA_DIR\\dct
vlib $DCT_DATA_DIR\\idct
vlib $DCT_DATA_DIR\\quantizer
vlib $DCT_DATA_DIR\\dctQidct

vmap work $DCT_DATA_DIR\\codelib
vmap common_da $DCT_DATA_DIR\\common_da
vmap dct $DCT_DATA_DIR\\dct
vmap idct $DCT_DATA_DIR\\idct
vmap quantizer $DCT_DATA_DIR\\quantizer
vmap dctQidct $DCT_DATA_DIR\\dctQidct


# Ver_03 = cut-through
# Ver_02= store-and-forward
# Note! encode_decode_system.vhdl defines constant wait_fifo_empty_c 
# it must be 0 for cut-through and 1 for store-and-forward!
#vcom -quiet -check_synthesis ../../../../IP/Interconnections/Mesh_2d/Vhdl/$MESH_VER/mesh_2d_pkg.vhd


vcom -quiet $HIBI_CVS_TREE/IP/Memories/Fifos/Fifo_Comparison/Vhdl/fifo_reg.vhd
vcom -quiet $HIBI_CVS_TREE/IP/Memories/Fifos/Fifo_Comparison/Vhdl/fifo_slotted_2.vhd

vcom -quiet $HIBI_CVS_TREE/IP/Platform/Synchronizer/Vhdl/aif*.vhd

# Kaannetaan hibin koodit
vcom -quiet $HIBI_SRC_DIR/hibiv2_pkg.vhd
vcom -quiet $HIBI_SRC_DIR/cfg_init_pkg.vhd
vcom -quiet $HIBI_SRC_DIR/addr_data_demuxes.vhd
vcom -quiet $HIBI_SRC_DIR/tx_ctrl.vhd
vcom -quiet $HIBI_SRC_DIR/addr_data_muxes.vhd
vcom -quiet $HIBI_SRC_DIR/addr_decoder.vhd
vcom -quiet $HIBI_SRC_DIR/cfg_mem.vhd
vcom -quiet $HIBI_SRC_DIR/double_fifo_demux_wr.vhd
vcom -quiet $HIBI_SRC_DIR/double_fifo_mux_rd.vhd
#vcom -quiet $HIBI_SRC_DIR/fifo.vhd
vcom -quiet $HIBI_CVS_TREE/IP/Memories/Fifos/Vhdl/multiclk_fifo.vhd
vcom -quiet $HIBI_SRC_DIR/fifo_muxes.vhd
vcom -quiet $HIBI_SRC_DIR/hibi_wrapper_r1.vhd
vcom -quiet $HIBI_SRC_DIR/receiver.vhd
vcom -quiet $HIBI_SRC_DIR/rx_ctrl.vhd
vcom -quiet $HIBI_SRC_DIR/transmitter.vhd
vcom -quiet $HIBI_SRC_DIR/hibi_wrapper_r3.vhd
vcom -quiet $HIBI_SRC_DIR/hibi_wrapper_r4.vhd
vcom -quiet $HIBI_SRC_DIR/hibi_wrapper_r3_top.vhd
vcom -quiet $HIBI_SRC_DIR/hibi_wrapper_r4_top.vhd
vcom -quiet $HIBI_SRC_DIR/async_fifo_interfaces.vhd
vcom -quiet $HIBI_SRC_DIR/hibi_bridge_v2.vhd
vcom -quiet $HIBI_SRC_DIR/eight_hibi_r4.vhd


# Käännetään system monitor
#vcom -quiet -check_synthesis ../Vhdl/system_monitor.vhd



#compile components for library [common_da]
vcom -93 -quiet -work common_da $DCTQIDCT_DIR/Vhdl/common_da/*.vhd

#compile components for library [dct]
vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT_pkg.vhd
vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/Rom_dct_sum.vhd
vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/Rom_dct_sub.vhd
vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT1D_DA.vhd
vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT_control.vhd
vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT_core.vhd
#vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT_core_tester.vhd
#vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT_core_tb.vhd

#compile components for library [idct]
vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_pkg.vhd
vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/Rom_idct_even.vhd
vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/Rom_idct_odd.vhd
vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_post_sum.vhd
vcom -93 -quiet  -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT1D_DA.vhd
vcom -93 -quiet  -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_control.vhd
vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_core.vhd
#vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_core_tester.vhd
#vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_core_tb.vhd

#compile components for library [quantizer]
vcom -93 -quiet -work quantizer $DCTQIDCT_DIR/Vhdl/quantizer/Quantizer_pkg.vhd
vcom -93 -quiet -work quantizer $DCTQIDCT_DIR/Vhdl/quantizer/IQuant.vhd

#compile components for library [dctQidct]
vcom -93 -quiet -work dctQidct $DCTQIDCT_DIR/Vhdl/dctQidct/IDCT_fifo.vhd
vcom -93 -quiet -work dctQidct $DCTQIDCT_DIR/Vhdl/dctQidct/dctQidct_core.vhd
#vcom -93 -quiet -work dctQidct $DCTQIDCT_DIR/Vhdl/dctQidct/dctQidct_core_tester.vhd
#vcom -93 -quiet -work dctQidct $DCTQIDCT_DIR/Vhdl/dctQidct/dctQidct_core_tb.vhd

#compile configuration for testbenches
#vcom -93 -quiet -work dct $DCTQIDCT_DIR/Vhdl/dct/DCT_core_tb_config.vhd
#vcom -93 -quiet -work idct $DCTQIDCT_DIR/Vhdl/idct/IDCT_core_tb_config.vhd
#vcom -93 -quiet -work dctQidct $DCTQIDCT_DIR/Vhdl/dctQidct/dctQidct_core_tb_config.vhd


# DCT_TO_HIBI
echo 'Compiling DCT_to_HIBI'
vcom -quiet -check_synthesis ../Vhdl/cl_cnt.vhd
vcom -quiet -check_synthesis ../Vhdl/dct_to_hibi_v2.vhd
vcom -quiet -check_synthesis ../Vhdl/dctqidct_top.vhd

# TESTBENCH
echo 'Compiling testbench'
vcom -quiet -check_synthesis ../Testbenches/tb_dct_package.vhd
vcom -quiet -check_synthesis ../Testbenches/tb_dct_cpu.vhd
vcom -quiet -check_synthesis ../Testbenches/tb_pinger.vhd
vcom -quiet -check_synthesis ../Testbenches/tb_dct_top.vhd


# Poistetaan vanha makefile ja tehdaan uusi
rm -f ../makefile.vhdl
vmake $DCT_DATA_DIR/codelib > $DCT_WORK_DIR/Simulation/makefile.vhd

echo "Create makefile complete "



